language: node_js
sudo: false
env:
  CXX=g++-4.8
node_js:
    - "stable"
before_script:
    - npm install -g gulp
script:
    - gulp test
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
